// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEosQrekDpbrXfH5SG6WRlP5ehz3oRPIY',
    appId: '1:532875674396:web:0eac3fe7e6ddf8ba1770d9',
    messagingSenderId: '532875674396',
    projectId: 'proyectofinal-9bf3c',
    authDomain: 'proyectofinal-9bf3c.firebaseapp.com',
    storageBucket: 'proyectofinal-9bf3c.appspot.com',
    measurementId: 'G-RS0M57EM81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRSEi1wCOhyef89PQkin_OXxnuxroQpog',
    appId: '1:532875674396:android:38a8caaa1b80e77e1770d9',
    messagingSenderId: '532875674396',
    projectId: 'proyectofinal-9bf3c',
    storageBucket: 'proyectofinal-9bf3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbbWJsM1P9KK4sAuu0rBkh_R02NorEa0',
    appId: '1:532875674396:ios:cbe2e1d9726e124d1770d9',
    messagingSenderId: '532875674396',
    projectId: 'proyectofinal-9bf3c',
    storageBucket: 'proyectofinal-9bf3c.appspot.com',
    iosBundleId: 'com.example.proyectoFinal',
  );
}
